### ISSUE TITLE
Transfer project to sugarlabs

### ISSUE THREAD

**Issue by davelab6** [lionaneesh/sugarlabs-calculate#3]
Please check out https://wiki.sugarlabs.org/go/Infrastructure_Team/Migrating_to_GitHub and transfer this repo to https://github.com/sugarlabs :)

**Comment by davelab6** [comment]
@lionaneesh please :)

**Comment by godiard** [comment]
@davelab6, this repository https://github.com/godiard/sugarlabs-calculate/commits/sugar-0.94 is newer than lioneesh. I can move it to sugarlabs

**Comment by davelab6** [comment]
@godiard great! please do! :)

**Comment by davelab6** [comment]
@godiard is https://github.com/lionaneesh/sugarlabs-calculate/pull/1 merged into your repo?

**Comment by godiard** [comment]
done

**Comment by walterbender** [comment]
thx

On Sun, Jun 5, 2016 at 7:41 PM, Gonzalo Odiard notifications@github.com
wrote:

> done
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/lionaneesh/sugarlabs-calculate/issues/3#issuecomment-223845066,
> or mute the thread
> https://github.com/notifications/unsubscribe/ADz74QDn2zGoDyuXY-ImgDef6rC-SS-Jks5qI16OgaJpZM4IlEAL
> .

## 

Walter Bender
Sugar Labs
http://www.sugarlabs.org
http://www.sugarlabs.org

**Comment by davelab6** [comment]
Thanks @godiard :)

**Comment by lionaneesh** [comment]
Thanks @godiard.
